import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import FormattedText from './FormattedText';
import MessageActionSheet from './MessageActionSheet';
import { IconBot, IconUser, IconCopy, IconCheck, IconEdit, IconMore } from './Icons';

function TypingDots({ palette }) {
  const styles = useMemo(() => createStyles(palette), [palette]); const [reduceMotion,setReduceMotion]=useState(false); const opacities=useRef([0,1,2].map(()=>new Animated.Value(.3))).current;
  useEffect(()=>{let mounted=true;AccessibilityInfo.isReduceMotionEnabled().then(v=>mounted&&setReduceMotion(Boolean(v)));const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduceMotion);return()=>{mounted=false;sub?.remove?.();};},[]);
  useEffect(()=>{if(reduceMotion){opacities.forEach(v=>v.setValue(.75));return;}const loops=opacities.map((opacity,index)=>Animated.loop(Animated.sequence([Animated.delay(index*140),Animated.timing(opacity,{toValue:1,duration:260,useNativeDriver:true}),Animated.timing(opacity,{toValue:.3,duration:260,useNativeDriver:true})])));loops.forEach(a=>a.start());return()=>loops.forEach(a=>a.stop());},[opacities,reduceMotion]);
  return <View style={styles.dotsRow} accessibilityLabel="Assistant is generating a response" accessibilityLiveRegion="polite">{opacities.map((opacity,index)=><Animated.View key={index} style={[styles.dot,{opacity}]}/>)}</View>;
}
const CompactAction=({label,onPress,children,palette})=><TouchableOpacity style={createStyles(palette).actionBtn} onPress={onPress} accessibilityLabel={label} accessibilityRole="button">{children}<Text style={createStyles(palette).actionText}>{label}</Text></TouchableOpacity>;
export default function MessageBubble({ message,isStreamingEmpty,palette,retryAvailable=false,onRetry=()=>{},onRegenerate=()=>{},onDownload=()=>{},onShare=()=>{},onContinue=()=>{},onBranch=()=>{},onBookmark=()=>{},onQuote=()=>{},onEdit=()=>{},onResubmit=()=>{},onSpeak=()=>{},onAddToDocument=()=>{},onDelete=()=>{} }){
  const styles=useMemo(()=>createStyles(palette),[palette]);const [copied,setCopied]=useState(false);const [actionsOpen,setActionsOpen]=useState(false);const moreRef=useRef(null);const isUser=message.role==='user';
  const handleCopy=async()=>{await Clipboard.setStringAsync(message.content||'');setCopied(true);setTimeout(()=>setCopied(false),1600);};
  return <><TouchableOpacity activeOpacity={1} onLongPress={()=>setActionsOpen(true)} delayLongPress={350} accessibilityRole="text" accessibilityHint="Long press for message actions"><View style={[styles.row,isUser?styles.rowUser:styles.rowAssistant]}>{!isUser&&<View style={styles.avatarBot} accessible={false}><IconBot size={16} color="#fff"/></View>}<View style={styles.column}><View style={[styles.bubble,isUser?styles.bubbleUser:styles.bubbleAssistant]}>{isUser?<Text style={styles.userText}>{message.content}</Text>:isStreamingEmpty?<TypingDots palette={palette}/>:<FormattedText text={message.content} palette={palette}/>}</View><View style={styles.actionRow}><CompactAction label={copied?'Copied':'Copy'} onPress={handleCopy} palette={palette}>{copied?<IconCheck size={14} color={palette.emerald}/>:<IconCopy size={14} color={palette.textFaint}/>}</CompactAction>{isUser&&<CompactAction label="Edit" onPress={onEdit} palette={palette}><IconEdit size={14} color={palette.textFaint}/></CompactAction>}<TouchableOpacity ref={moreRef} style={styles.actionBtn} onPress={()=>setActionsOpen(true)} accessibilityLabel="More" accessibilityRole="button"><IconMore size={15} color={palette.textFaint}/><Text style={styles.actionText}>More</Text></TouchableOpacity></View></View>{isUser&&<View style={styles.avatarUser} accessible={false}><IconUser size={16} color={palette.textMuted}/></View>}</View></TouchableOpacity><MessageActionSheet visible={actionsOpen} message={message} onClose={()=>setActionsOpen(false)} palette={palette} onCopy={handleCopy} onCopyMarkdown={handleCopy} onQuote={onQuote} onEdit={onEdit} onResubmit={onResubmit} onRetry={onRetry} onRegenerate={onRegenerate} onContinue={onContinue} onBranch={onBranch} onBookmark={onBookmark} onSpeak={onSpeak} onAddToDocument={onAddToDocument} onShare={onShare} onDownload={onDownload} retryAvailable={retryAvailable} onDelete={onDelete} returnFocusRef={moreRef}/></>;
}
const createStyles=(c)=>StyleSheet.create({row:{flexDirection:'row',width:'100%',marginBottom:20},rowUser:{justifyContent:'flex-end'},rowAssistant:{justifyContent:'flex-start'},column:{maxWidth:'90%'},avatarBot:{width:32,height:32,borderRadius:11,backgroundColor:c.cyan,alignItems:'center',justifyContent:'center',marginRight:9,marginTop:3},avatarUser:{width:32,height:32,borderRadius:11,backgroundColor:c.surfaceElevated,borderWidth:1,borderColor:c.borderLight,alignItems:'center',justifyContent:'center',marginLeft:9,marginTop:3},bubble:{borderRadius:18,padding:15},bubbleUser:{backgroundColor:c.cyan,borderTopRightRadius:6},bubbleAssistant:{backgroundColor:c.surfaceElevated,borderWidth:1,borderColor:c.border,borderTopLeftRadius:6},userText:{color:c.userText,fontSize:14,lineHeight:20},actionRow:{flexDirection:'row',gap:6,marginTop:8},actionBtn:{minHeight:48,flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:10,justifyContent:'center',backgroundColor:c.panelAlt,borderWidth:1,borderColor:c.border,borderRadius:999},actionText:{fontSize:9,fontWeight:'800',color:c.textMuted},dotsRow:{flexDirection:'row',gap:6,paddingVertical:4,alignItems:'center',height:16},dot:{width:6,height:6,borderRadius:3,backgroundColor:c.cyanBright}});
