import React, { useMemo } from 'react';
import { Modal, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IconClose, IconDownload, IconTrash } from './Icons';
import { radii } from '../theme';
import { useModalAccessibilityFocus, useReducedMotion } from '../ui/primitives';

export default function SettingsSheet({ visible, onClose, onExportChat, onExportPdf = () => {}, onExportPdfCompact = () => {}, onCreateDocumentZip = () => {}, onClearChat, onExportData = () => {}, onImportData = () => {}, onBackup = () => {}, onRestore = () => {}, dataStats = {}, colorMode, onToggleColorMode, offlineMode = false, onToggleOfflineMode = () => {}, voiceLocale = 'en-GB', onChangeVoiceLocale = () => {}, playbackSpeed = 1, onChangePlaybackSpeed = () => {}, onStopSpeech = () => {}, hapticsEnabled = true, onToggleHaptics = () => {}, palette, returnFocusRef }) {
  const styles = useMemo(() => createStyles(palette), [palette]);
  const reducedMotion = useReducedMotion();
  const modalTitleRef = useModalAccessibilityFocus(visible, returnFocusRef);
  const insets = useSafeAreaInsets();
  return <Modal visible={visible} animationType={reducedMotion ? 'none' : 'slide'} transparent onRequestClose={onClose}><View style={styles.backdrop}><TouchableOpacity style={StyleSheet.absoluteFill} activeOpacity={1} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close app settings" /><View style={[styles.sheet, { paddingBottom: Math.max(insets.bottom, 12) }]} accessibilityViewIsModal><View style={styles.header}><Text ref={modalTitleRef} accessible accessibilityRole="header" style={styles.title}>Command Centre Settings</Text><TouchableOpacity style={styles.closeBtn} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close app settings"><IconClose color={palette.textMuted} /></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag">
    <View style={styles.row}><View style={{ flex: 1, paddingRight: 12 }}><Text style={styles.rowTitle}>Dark mode</Text><Text style={styles.rowDetail}>{colorMode === 'dark' ? 'Dark appearance is on.' : 'Light appearance is on. Toggle for dark theme.'}</Text></View><Switch value={colorMode === 'dark'} onValueChange={onToggleColorMode} accessibilityLabel="Toggle dark mode" trackColor={{ false: palette.border, true: palette.cyan }} thumbColor={colorMode === 'dark' ? palette.cyanBright : '#f4f4f5'} /></View>
    <View style={styles.row}><View style={{ flex: 1, paddingRight: 12 }}><Text style={styles.rowTitle}>Offline draft mode</Text><Text style={styles.rowDetail}>{offlineMode ? 'Messages queue locally until you go back online.' : 'Online — sends to OpenRouter when you submit.'}</Text></View><Switch value={!!offlineMode} onValueChange={onToggleOfflineMode} accessibilityLabel="Toggle offline draft mode" trackColor={{ false: palette.border, true: palette.cyan }} thumbColor={offlineMode ? palette.cyanBright : '#f4f4f5'} /></View>
    <View style={styles.row}><View><Text style={styles.rowTitle}>Speech locale</Text><Text style={styles.rowDetail}>Current device transcription locale: {voiceLocale}.</Text></View><TouchableOpacity style={styles.localeButton} onPress={() => onChangeVoiceLocale(voiceLocale === 'en-GB' ? 'en-US' : 'en-GB')} accessibilityRole="button"><Text style={styles.localeText}>Change</Text></TouchableOpacity></View>
    <View style={styles.row}><View><Text style={styles.rowTitle}>Haptic feedback</Text><Text style={styles.rowDetail}>Use restrained tactile feedback for selected confirmations and navigation actions.</Text></View><Switch value={hapticsEnabled} onValueChange={onToggleHaptics} accessibilityLabel="Toggle haptic feedback" /></View>
    <View style={styles.row}><View><Text style={styles.rowTitle}>TTS playback speed</Text><Text style={styles.rowDetail}>Device/media setting: {Number(playbackSpeed).toFixed(1)}×. This does not change model behaviour.</Text></View><TouchableOpacity style={styles.localeButton} onPress={() => onChangePlaybackSpeed(playbackSpeed >= 1.5 ? 0.8 : Number((playbackSpeed + 0.1).toFixed(1)))} accessibilityRole="button"><Text style={styles.localeText}>Change</Text></TouchableOpacity></View>
    <TouchableOpacity style={styles.action} onPress={onStopSpeech} accessibilityRole="button"><Text style={styles.importGlyph}>■</Text><Text style={styles.actionText}>Stop text to speech</Text></TouchableOpacity>
    <View style={styles.info}><Text style={styles.infoTitle}>Local Data Management</Text><Text style={styles.infoText}>Schema {dataStats.schema || '—'} · {dataStats.chats || 0} chats · {dataStats.archived || 0} archived · {dataStats.attachments || 0} attachment records · {dataStats.queued || 0} queued drafts.</Text><Text style={styles.infoText}>Exports exclude secrets, PIN verifier data and transient extraction context.</Text></View>
    <View style={styles.documentStudio}><Text style={styles.documentStudioTitle}>Document Studio</Text><Text style={styles.documentStudioDetail}>Create polished local documents and portable chat bundles. All options exclude secrets and transient request context.</Text></View><TouchableOpacity style={styles.action} onPress={onExportChat} accessibilityRole="button"><IconDownload size={17} color={palette.cyanBright} /><Text style={styles.actionText}>Export current chat as text</Text></TouchableOpacity><TouchableOpacity style={[styles.action, styles.primaryAction]} onPress={onExportPdf} accessibilityRole="button"><IconDownload size={17} color="#ffffff" /><Text style={[styles.actionText, styles.primaryActionText]}>Create current chat as local PDF</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onExportPdfCompact} accessibilityRole="button"><IconDownload size={17} color={palette.cyanBright} /><Text style={styles.actionText}>Create compact transcript PDF</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onCreateDocumentZip} accessibilityRole="button"><Text style={styles.importGlyph}>▣</Text><Text style={styles.actionText}>Create safe document ZIP bundle</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onExportData} accessibilityRole="button"><IconDownload size={17} color={palette.cyanBright} /><Text style={styles.actionText}>Export current chat as safe JSON</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onImportData} accessibilityRole="button"><Text style={styles.importGlyph}>⇩</Text><Text style={styles.actionText}>Import validated chat JSON</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onBackup} accessibilityRole="button"><Text style={styles.importGlyph}>⇧</Text><Text style={styles.actionText}>Create validated ordinary backup</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={onRestore} accessibilityRole="button"><Text style={styles.importGlyph}>⇩</Text><Text style={styles.actionText}>Preview and restore validated backup</Text></TouchableOpacity><TouchableOpacity style={[styles.action, styles.clearAction]} onPress={onClearChat} accessibilityRole="button"><IconTrash size={17} color={palette.rose} /><Text style={[styles.actionText, styles.clearText]}>Clear current chat</Text></TouchableOpacity>
    <Text style={styles.privacy}>Attachment text used for a request is transient. This ordinary settings area cannot edit provider, model, generation, instruction, prompt or credential configuration.</Text>
  </ScrollView></View></View></Modal>;
}

const createStyles = (colors) => StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.bg, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: 1, borderColor: colors.border, minHeight: '60%', maxHeight: '90%' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.textPrimary, fontSize: 16, fontWeight: '700' }, closeBtn: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.panel, borderRadius: radii.sm }, content: { padding: 16, gap: 10 }, row: { minHeight: 60, padding: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, rowTitle: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' }, rowDetail: { color: colors.textFaint, fontSize: 10, marginTop: 3, maxWidth: 230 }, localeButton: { minHeight: 48, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyanDim, borderRadius: radii.sm }, localeText: { color: colors.cyanBright, fontWeight: '700', fontSize: 11 }, info: { padding: 12, backgroundColor: colors.panelAlt, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, infoTitle: { color: colors.cyanBright, fontSize: 12, fontWeight: '700', marginBottom: 5 }, documentStudio: { padding: 12, backgroundColor: colors.cyanDim, borderWidth: 1, borderColor: colors.cyanBorder, borderRadius: radii.md }, documentStudioTitle: { color: colors.cyanBright, fontSize: 12, fontWeight: '800', marginBottom: 4 }, documentStudioDetail: { color: colors.textMuted, fontSize: 10, lineHeight: 15 }, infoText: { color: colors.textMuted, fontSize: 10, lineHeight: 16 }, action: { minHeight: 48, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, borderRadius: radii.md }, actionText: { color: colors.textSecondary, fontSize: 12, fontWeight: '600' }, primaryAction: { backgroundColor: colors.cyan, borderColor: colors.cyan }, primaryActionText: { color: '#ffffff' }, importGlyph: { color: colors.cyanBright, fontSize: 18 }, clearAction: { borderColor: colors.rose }, clearText: { color: colors.rose }, privacy: { color: colors.textFaint, fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 4 },
});
